(function (root) {
  const reg = (id, tab, title, description, path, name, value, type = 'DWord') => ({ id, tab, title, description, path, name, value, type });
  const catalog = [
    reg('edge-sleeping-tabs', 'performance', 'Enable Edge sleeping tabs', 'Lets idle tabs sleep to reduce browser CPU and memory usage. May already be enabled. Not applied to personal Microsoft-account browser profiles; organization policy can override.', 'HKCU:\\Software\\Policies\\Microsoft\\Edge', 'SleepingTabsEnabled', 1),
    reg('edge-network-prediction', 'performance', 'Disable Edge page preloading', 'Stops speculative page loads and preconnections. Sites may load more slowly. Not applied to personal Microsoft-account browser profiles; not a server-ping fix.', 'HKCU:\\Software\\Policies\\Microsoft\\Edge', 'NetworkPredictionOptions', 2),
    reg('edge-gpu-acceleration', 'performance', 'Disable Edge graphics acceleration', 'Moves supported browser rendering away from GPU acceleration. Can increase CPU use and make video less smooth. Restart Edge; test with your own workload.', 'HKCU:\\Software\\Policies\\Microsoft\\Edge', 'HardwareAccelerationModeEnabled', 0),
    reg('edge-startup-only', 'performance', 'Turn off Edge Startup Boost', 'Stops Edge preloading at sign-in. Close and reopen Edge after applying. May be managed by your organization.', 'HKCU:\\Software\\Policies\\Microsoft\\Edge', 'StartupBoostEnabled', 0),
    reg('edge-background-only', 'performance', 'Stop Edge background extensions', 'Stops extensions and apps continuing after the last Edge window closes. Restart Edge; background notifications may stop.', 'HKCU:\\Software\\Policies\\Microsoft\\Edge', 'BackgroundModeEnabled', 0),
    reg('pointer-trails', 'performance', 'Remove pointer trails', 'Removes the trailing desktop pointer effect. Does not change raw mouse input or game sensitivity. Sign out to refresh.', 'HKCU:\\Control Panel\\Mouse', 'MouseTrails', '0', 'String'),
    reg('keyboard-repeat', 'performance', 'Short keyboard repeat delay', 'Uses the shortest Windows delay before a held key repeats. This affects typing, not game input latency. Sign out to refresh.', 'HKCU:\\Control Panel\\Keyboard', 'KeyboardDelay', '0', 'String'),
    reg('keyboard-repeat-speed', 'performance', 'Fast keyboard repeat rate', 'Sets a faster Windows repeat rate for held keys. This affects typing and menus, not game input latency. Sign out to refresh.', 'HKCU:\\Control Panel\\Keyboard', 'KeyboardSpeed', '31', 'String'),
    reg('game-bar-tips', 'performance', 'Hide Game Bar tips', 'Turns off Game Bar startup tips and prompts. It does not remove Game Bar.', 'HKCU:\\Software\\Microsoft\\GameBar', 'ShowStartupPanel', 0),
    reg('game-dvr-audio', 'performance', 'Disable Game DVR audio capture', 'Stops Windows Game DVR from capturing audio with background clips. Re-enable if you use Game DVR recordings.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR', 'AudioCaptureEnabled', 0),
    reg('desktop-menu-delay', 'performance', 'Reduce desktop menu delay', 'Makes Windows menus open faster. This only affects desktop menus and does not change game latency.', 'HKCU:\\Control Panel\\Desktop', 'MenuShowDelay', '0', 'String'),
    reg('mouse-hover-delay', 'performance', 'Reduce mouse hover delay', 'Makes Windows hover tooltips and folder previews appear faster. This does not change in-game mouse input.', 'HKCU:\\Control Panel\\Mouse', 'MouseHoverTime', '100', 'String'),
    reg('mouse-snap-default', 'performance', 'Disable mouse snap-to button', 'Stops Windows moving the pointer to default dialog buttons. This is a desktop preference, not an in-game setting.', 'HKCU:\\Control Panel\\Mouse', 'SnapToDefaultButton', '0', 'String'),
    reg('game-mode-notifications', 'performance', 'Hide Game Mode notifications', 'Stops Windows showing Game Mode notifications while a game is active.', 'HKCU:\\Software\\Microsoft\\GameBar', 'ShowGameModeNotifications', 0),
    reg('capture-cursor', 'performance', 'Disable Game DVR cursor capture', 'Stops background Game DVR clips capturing the mouse cursor.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR', 'CursorCaptureEnabled', 0),
    reg('drag-full-windows', 'performance', 'Show window contents while dragging', 'Keeps window contents visible while dragging. This is a desktop preference, not an FPS setting.', 'HKCU:\\Control Panel\\Desktop', 'DragFullWindows', '1', 'String'),
    reg('clipboard-history', 'stealth', 'Disable clipboard history', 'Stops Windows saving new clipboard-history entries. Existing entries are not erased.', 'HKCU:\\Software\\Microsoft\\Clipboard', 'EnableClipboardHistory', 0),
    reg('clipboard-sync', 'stealth', 'Disable cloud clipboard sync', 'Stops clipboard contents syncing between Windows devices for this account.', 'HKCU:\\Software\\Microsoft\\Clipboard', 'CloudClipboardAutomaticUpload', 0),
    reg('typing-personalization', 'stealth', 'Disable typing personalization', 'Turns off implicit collection of typed text for input personalization. Sign out to refresh.', 'HKCU:\\Software\\Microsoft\\InputPersonalization', 'RestrictImplicitTextCollection', 1),
    reg('inking-personalization', 'stealth', 'Disable inking personalization', 'Turns off implicit handwriting collection for input personalization. Sign out to refresh.', 'HKCU:\\Software\\Microsoft\\InputPersonalization', 'RestrictImplicitInkCollection', 1),
    reg('search-history', 'stealth', 'Disable device search history', 'Stops Windows Search from saving new device search history for this account.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings', 'IsDeviceSearchHistoryEnabled', 0),
    reg('cloud-search', 'stealth', 'Disable cloud search results', 'Stops Windows Search from showing cloud content from connected personal accounts.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings', 'IsMSACloudSearchEnabled', 0),
    reg('tailored-ads', 'stealth', 'Disable tailored app advertising', 'Stops Windows apps from using the advertising ID for tailored ads.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo', 'Enabled', 0),
    reg('content-suggestions', 'stealth', 'Disable suggested app content', 'Turns off automatically suggested content in Windows Start and app surfaces.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager', 'SubscribedContent-338389Enabled', 0),
    reg('lock-screen-tips', 'stealth', 'Disable lock-screen tips', 'Turns off Windows tips and suggestions on the lock screen.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager', 'RotatingLockScreenOverlayEnabled', 0),
    reg('start-recent-items', 'stealth', 'Hide recent Start items', 'Stops Start from showing recently opened items. It does not delete your files or app history.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Start', 'ShowRecentList', 0),
    reg('feedback-notifications', 'stealth', 'Reduce feedback prompts', 'Stops Windows showing frequent feedback-notification prompts.', 'HKCU:\\Software\\Microsoft\\Siuf\\Rules', 'NumberOfSIUFInPeriod', 0),
    reg('app-suggestions', 'stealth', 'Disable Start app suggestions', 'Turns off suggested apps in Start for the current account.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager', 'SubscribedContent-338388Enabled', 0),
    reg('input-insights', 'stealth', 'Disable input data sharing', 'Turns off a Windows input-personalization setting for the current account.', 'HKCU:\\Software\\Microsoft\\InputPersonalization', 'AllowInputPersonalization', 0),
    reg('explorer-compact', 'shell', 'Compact Explorer spacing', 'Uses smaller spacing between files in Windows 11 Explorer. Close and reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'UseCompactMode', 1),
    reg('explorer-process', 'shell', 'Separate folder process', 'Launches folder windows in a separate Explorer process. May use more memory; sign out to refresh.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'SeparateProcess', 1),
    reg('explorer-status', 'shell', 'Show Explorer status bar', 'Shows file counts and selection information at the bottom of Explorer. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'ShowStatusBar', 1),
    reg('explorer-fullpath', 'shell', 'Full path in Explorer title', 'Displays the full folder path in Explorer title bars. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CabinetState', 'FullPath', 1),
    reg('explorer-all-folders', 'shell', 'Show all folders in navigation', 'Shows the full folder tree in File Explorer navigation. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'NavPaneShowAllFolders', 1),
    reg('explorer-expand-current', 'shell', 'Expand to current folder', 'Makes Explorer’s navigation pane follow the current folder. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'NavPaneExpandToCurrentFolder', 1),
    reg('explorer-checkboxes', 'shell', 'Show item check boxes', 'Adds check boxes beside files and folders for easier multi-selection. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'AutoCheckSelect', 1),
    reg('explorer-empty-drives', 'shell', 'Show empty drives', 'Shows empty removable drives in This PC. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'HideDrivesWithNoMedia', 0),
    reg('explorer-sync-provider', 'shell', 'Hide sync-provider notifications', 'Hides Windows Explorer notifications from cloud-sync providers. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'ShowSyncProviderNotifications', 0),
    reg('explorer-launch-this-pc', 'shell', 'Open Explorer to This PC', 'Makes new File Explorer windows open at This PC. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'LaunchTo', 1),
    reg('explorer-libraries', 'shell', 'Show Libraries in Explorer', 'Shows the Libraries node in Explorer navigation. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'NavPaneShowLibraries', 1),
    reg('explorer-hidden-protected', 'shell', 'Show protected system files', 'Shows protected operating-system files in Explorer. Use carefully; re-open Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'ShowSuperHidden', 1),
    reg('explorer-preview-pane', 'shell', 'Allow Explorer preview handlers', 'Allows installed preview handlers to render files in the preview pane. Open the pane separately with Alt+P.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'ShowPreviewHandlers', 1),
    reg('explorer-details-pane', 'shell', 'Show file information tooltips', 'Shows file information when hovering over Explorer items. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'ShowInfoTip', 1),
    reg('explorer-restore-windows', 'shell', 'Restore folder windows at sign-in', 'Reopens the folder windows that were open before sign-out. Sign out to refresh.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'PersistBrowsers', 1),
    reg('window-animation', 'personalize', 'Reduce minimize animations', 'Turns off desktop minimize and maximize animation. Sign out to refresh; not an in-game FPS setting.', 'HKCU:\\Control Panel\\Desktop\\WindowMetrics', 'MinAnimate', '0', 'String'),
    reg('taskbar-animation', 'personalize', 'Reduce taskbar animations', 'Turns off taskbar button animations. Sign out to refresh.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'TaskbarAnimations', 0),
    reg('explorer-recent', 'personalize', 'Hide recent files in Home', 'Hides the recent-files section of Explorer Home without deleting any files. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer', 'ShowRecent', 0),
    reg('explorer-frequent', 'personalize', 'Hide frequent folders in Home', 'Hides frequent folders in Explorer Home without deleting folders. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer', 'ShowFrequent', 0)
    ,reg('titlebar-accent', 'personalize', 'Use accent color on title bars', 'Shows your Windows accent color on supported title bars and borders. Sign out to refresh.', 'HKCU:\\Software\\Microsoft\\Windows\\DWM', 'ColorPrevalence', 1)
    ,reg('taskbar-badges', 'personalize', 'Hide taskbar app badges', 'Turns off notification count badges on taskbar buttons. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'TaskbarBadges', 0)
    ,reg('taskbar-flash', 'personalize', 'Reduce taskbar flashing', 'Stops taskbar buttons flashing for attention. Reopen Explorer.', 'HKCU:\\Control Panel\\Desktop', 'ForegroundFlashCount', 0)
    ,reg('snap-assist-suggestions', 'personalize', 'Hide Snap Assist suggestions', 'Stops Windows showing suggested apps when arranging windows with Snap Assist.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'SnapAssist', 0)
    ,reg('desktop-icons', 'personalize', 'Show desktop icons', 'Shows normal desktop icons. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'HideIcons', 0)
    ,reg('notification-center', 'personalize', 'Disable notification center', 'Turns off the current-user notification center policy. You may miss app notifications.', 'HKCU:\\Software\\Policies\\Microsoft\\Windows\\Explorer', 'DisableNotificationCenter', 1)
    ,reg('storage-sense', 'maintenance', 'Enable Storage Sense', 'Enables Windows Storage Sense for this account. Its cleanup schedule remains controlled by Windows Settings.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\StorageSense\\Parameters\\StoragePolicy', '01', 1)
    ,reg('thumbnail-cache', 'maintenance', 'Enable thumbnail cache', 'Lets Explorer save image and video thumbnails for faster folder browsing. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced', 'DisableThumbnailCache', 0)
    ,reg('recycle-confirmation', 'maintenance', 'Show Recycle Bin confirmation', 'Asks for confirmation before moving files to Recycle Bin. Reopen Explorer.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer', 'ConfirmFileDelete', 1)
    ,reg('storage-low-space-notices', 'maintenance', 'Show low-disk-space notices', 'Keeps Windows low-disk-space notifications enabled so cleanup is not missed.', 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer', 'NoLowDiskSpaceChecks', 0)
    ,reg('error-reporting', 'maintenance', 'Disable Windows Error Reporting', 'Stops Windows Error Reporting from sending crash reports. This can reduce background reporting after crashes.', 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting', 'Disabled', 1)
  ];
  const apps = [
    ['clipchamp', 'Clipchamp', 'Clipchamp.Clipchamp'], ['onenote', 'OneNote for Windows', 'Microsoft.Office.OneNote'],
    ['solitaire', 'Solitaire Collection', 'Microsoft.MicrosoftSolitaireCollection'], ['weather', 'Weather', 'Microsoft.BingWeather'],
    ['news', 'Microsoft News', 'Microsoft.BingNews'], ['feedback', 'Feedback Hub', 'Microsoft.WindowsFeedbackHub'],
    ['maps', 'Windows Maps', 'Microsoft.WindowsMaps'], ['todo', 'Microsoft To Do', 'Microsoft.Todos'],
    ['clock', 'Windows Clock', 'Microsoft.WindowsAlarms'], ['camera', 'Windows Camera', 'Microsoft.WindowsCamera'],
    ['media-player', 'Media Player', 'Microsoft.ZuneMusic'], ['movies-tv', 'Movies & TV', 'Microsoft.ZuneVideo'],
    ['people', 'People', 'Microsoft.People'], ['get-help', 'Get Help', 'Microsoft.GetHelp'],
    ['get-started', 'Get Started', 'Microsoft.Getstarted'], ['office-hub', 'Office Hub', 'Microsoft.MicrosoftOfficeHub'],
    ['skype', 'Skype', 'Microsoft.SkypeApp'], ['3d-viewer', '3D Viewer', 'Microsoft.Microsoft3DViewer'],
    ['mixed-reality', 'Mixed Reality Portal', 'Microsoft.MixedReality.Portal'], ['power-automate', 'Power Automate', 'Microsoft.PowerAutomateDesktop']
    ,['phone-link', 'Phone Link', 'Microsoft.YourPhone'], ['outlook', 'Outlook for Windows', 'Microsoft.OutlookForWindows'],
    ['teams', 'Microsoft Teams', 'MSTeams'], ['xbox-overlay', 'Xbox Game Bar', 'Microsoft.XboxGamingOverlay'],
    ['xbox-identity', 'Xbox Identity Provider', 'Microsoft.XboxIdentityProvider'], ['xbox-speech', 'Xbox Speech Overlay', 'Microsoft.XboxSpeechToTextOverlay'],
    ['dev-home', 'Dev Home', 'Microsoft.Windows.DevHome'], ['quick-assist', 'Quick Assist', 'MicrosoftCorporationII.QuickAssist'],
    ['cortana', 'Cortana', 'Microsoft.549981C3F5F10'], ['paint-3d', 'Paint 3D', 'Microsoft.MSPaint']
  ].map(([id, title, packageName]) => ({ id, title, packageName }));
  if (typeof module !== 'undefined') module.exports = { catalog, apps };
  else root.tweakCatalog = { catalog, apps };
})(typeof window === 'undefined' ? globalThis : window);
