const { app, BrowserWindow } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'batman-ui-test-')));
app.whenReady().then(async () => {
  const win = new BrowserWindow({ width:1280, height:900, show:false, webPreferences:{ preload:path.join(__dirname,'mock-preload.cjs'), contextIsolation:true, backgroundThrottling:false, offscreen:true } });
  const errors=[]; win.webContents.on('console-message', (_event, level, message) => { if (level >= 3 && !message.includes('resource')) errors.push(message); });
  // Testing is offline and uses only the mock preload: no Windows commands or user profile.
  win.webContents.session.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']}, (_details, cb) => cb({cancel:true}));
  try {
    await win.loadFile(path.join(process.env.BATMAN_UI_ROOT || path.join(__dirname,'..'),'index.html'));
    const run = code => win.webContents.executeJavaScript(`{ ${code} }`);
    const assert = (value, label) => { if (!value) throw new Error(label); console.log('PASS ' + label); };
    assert(await run("document.querySelectorAll('[data-tweak=\"keyboard-repeat\"]').length === 1"), 'new catalog renders');
    const output = path.join(__dirname,'..','qa-output'); fs.mkdirSync(output,{recursive:true});
    fs.writeFileSync(path.join(output,'login.png'), (await win.webContents.capturePage()).toPNG());
    await run("document.getElementById('login-username').value='DEVELOPER'; document.getElementById('login-password').value='batmaniscool-dev'; document.getElementById('login-password').form.requestSubmit()");
    await new Promise(resolve => setTimeout(resolve,2000));
    assert(await run("document.getElementById('bat-login-overlay').style.display === 'none'"), 'existing developer login works');
    assert(await run("!document.getElementById('first-run-welcome').hidden"), 'first-run welcome appears after sign-in');
    await run("document.getElementById('btn-complete-welcome').click()");
    assert(await run("document.getElementById('first-run-welcome').hidden && localStorage.getItem('batmaniscool_first_run_seen') === 'true'"), 'welcome completion stays local');
    await run("document.querySelector('[data-tab=\"tab-performance\"]').click(); document.querySelector('[data-tuning-profile=\"extreme\"]').click(); document.querySelector('[data-tuning-profile=\"low\"]').click()");
    assert(await run("document.getElementById('pending-count-label').textContent === '9' && document.querySelector('[data-tweak-id=\"power-min\"]').value === ''"), 'lower profile replaces extreme queue and dropdowns');
    assert(await run('window.testHarness.calls().length === 0'), 'profile selection never executes tweaks');
    await run("document.getElementById('btn-reset-pending').click(); const select=document.querySelector('[data-tweak-id=\"power-epp\"]'); select.value='100'; select.dispatchEvent(new Event('change')); document.querySelector('[data-tuning-profile=\"extreme\"]').click(); document.querySelector('[data-tuning-profile=\"low\"]').click()");
    assert(await run("document.querySelector('[data-tweak-id=\"power-epp\"]').value==='100' && document.getElementById('pending-count-label').textContent==='10'"), 'profile switching preserves prior manual dropdown selection');
    await run("document.getElementById('btn-reset-pending').click(); document.querySelector('[data-power-id=\"power-epp\"]').click(); document.querySelector('#tab-performance .queued-filter').click()");
    assert(await run("document.querySelectorAll('#tab-performance .tweak-card:not([hidden])').length===1 && window.testHarness.calls().length===0"), 'original restore only queues and queued-only filters cards');
    await run("document.querySelector('#tab-performance .queued-filter').click()");
    await run("document.getElementById('btn-reset-pending').click(); const search=document.querySelector('#tab-performance input[type=search]'); search.value='keyboard'; search.dispatchEvent(new Event('input'))");
    assert(await run("document.querySelectorAll('#tab-performance .tweak-card:not([hidden])').length===2"), 'search narrows cards');
    await run("document.querySelector('[data-tweak=\"keyboard-repeat\"] .tweak-info-btn').click(); document.getElementById('btn-queue-drawer-tweak').click()");
    await run("document.getElementById('btn-apply-pending').click()");
    await new Promise(resolve => setTimeout(resolve,100));
    assert(await run("document.getElementById('pending-count-label').textContent==='1' && window.testHarness.calls()[0].payload.enabled===true"), 'drawer sends valid payload and failures remain queued');
    await run("document.getElementById('btn-reset-pending').click(); document.querySelector('[data-tab=\"tab-debloat\"]').click(); document.querySelector('[data-debloat-profile=\"clipchamp\"]').click(); document.querySelector('[data-debloat-profile=\"weather\"]').click()");
    assert(await run("document.getElementById('pending-count-label').textContent==='2' && window.testHarness.calls().length===1"), 'independent debloat selections only queue');
    await run("document.getElementById('btn-apply-pending').click()");
    await new Promise(resolve => setTimeout(resolve,100));
    assert(await run("document.getElementById('pending-count-label').textContent==='0' && window.testHarness.calls().length===3"), 'successful queue items clear');
    await run("document.getElementById('btn-reset-pending').click(); window.confirm=()=>true; document.getElementById('btn-queue-full-debloat').click()");
    assert(await run("document.getElementById('pending-count-label').textContent==='1' && window.testHarness.calls().length===3"), 'full debloat only queues a single curated action');
    await run("document.getElementById('btn-apply-pending').click()");
    await new Promise(resolve => setTimeout(resolve,100));
    assert(await run("window.testHarness.calls().at(-1).id==='debloat-full' && window.testHarness.calls().at(-1).payload.profile==='full'"), 'full debloat reaches the backend only after Apply');
    await run("const select=document.querySelector('[data-tweak-id=\"power-epp\"]'); select.value='0'; select.dispatchEvent(new Event('change')); document.getElementById('btn-apply-pending').click()");
    await new Promise(resolve => setTimeout(resolve,100));
    assert(await run("window.testHarness.calls().at(-1).payload.value==='0' && JSON.parse(localStorage.getItem('batmaniscool_change_history'))[0].inverse.restore===true"), 'selected power value reaches mock backend and saved-value undo is recorded');
    await run("document.querySelector('[data-power-id=\"power-epp\"]').click(); document.getElementById('btn-apply-pending').click()");
    await new Promise(resolve => setTimeout(resolve,100));
    assert(await run("window.testHarness.calls().at(-1).payload.restore===true && document.getElementById('pending-count-label').textContent==='0'"), 'power restore payload reaches mock backend only after Apply');
    await run("document.querySelector('[data-tab=\"tab-performance\"]').click(); const search=document.querySelector('#tab-performance input[type=search]'); search.value=''; search.dispatchEvent(new Event('input')); document.querySelector('.main-viewport').scrollTop=0");
    await run("document.getElementById('toast-area').replaceChildren()");
    await new Promise(resolve => setTimeout(resolve,400));
    fs.writeFileSync(path.join(output,'performance.png'), (await win.webContents.capturePage()).toPNG());
    win.setSize(980,680); await new Promise(resolve => setTimeout(resolve,100));
    assert(await run("[...document.querySelectorAll('#tab-performance .tweak-card')].every(el => el.scrollWidth <= el.clientWidth + 2)"), 'cards do not overflow at minimum window size');
    fs.writeFileSync(path.join(output,'compact.png'), (await win.webContents.capturePage()).toPNG());
    await run("document.querySelectorAll('.category-navigation button')[1].click()");
    await new Promise(resolve => setTimeout(resolve,800));
    assert(await run("[...document.querySelectorAll('.power-actions')].every(el => el.scrollWidth <= el.clientWidth + 2)"), 'power dropdowns and restore buttons fit compact cards');
    fs.writeFileSync(path.join(output,'power-controls.png'), (await win.webContents.capturePage()).toPNG());
    assert(!errors.length, 'no renderer script errors: ' + errors.join(';'));
    console.log('UI smoke tests complete; all system changes mocked.'); app.exit(0);
  } catch (error) { console.error(error.stack); app.exit(1); }
});
